### PR TITLE
refactor: ntex version and some clippy warning

### PR DESCRIPTION
**Pull request by leon3s**
Hey i started to investigate a version problem when using `ntex-files` and it's seems that `hyperx` is [unmaintained](https://github.com/dekellum/hyperx/issues/39).
I could find a workaround by removing one dependency that my project use it came from `Url` but it could be problematic in some other cases. Should we fork `hyperx` maybe ?

Since i was inside the code i upgraded the version to ntex 0.6.5 and did fix some clippy warning along the way

### CODE REVIEW

**Comment by leon3s** [comment]
Also do you mind to upgrade the CI 1.56 to 1.65 since it's seem to be the required version for ntex ?

**Comment by fafhrd91** [comment]
i think you should port ntex-files from actix, it should have some recent changes. overall, i am not big fan of forking hyperx, too much maintenance work. could we maybe fork only required functionality?

for msrv use whatever ntex uses

**Comment by leon3s** [comment]
For what i saw we only use some Header helper like `DispositionType`, `HttpDate`, `DispositionParam` and others, maybe we could just copy them into `ntex-http::header` and make them accessible under a feature ?
I can rewrite actix-file implementation aswell but will take a bit more time.

**Comment by fafhrd91** [comment]
lets copy impls to ntex-files itself, i dont want to add unnecessary maintenance work to ntex-http. it is up to you if you want to copy actix impl or keep current. either way is fine with me

**Comment by leon3s** [comment]
I'll copy their file with the required dependencies inside `ntex-files` since it's the quicker way to fix the problem i think. And i can see to port the `actix-files` later it may be cleaner.
But i'll do it on another pull request, we can merge this one if you don't mind!

**Review by fafhrd91 — APPROVED** [review]

**Comment by fafhrd91** [comment]
i think you should be able to publish new version

**Comment by leon3s** [comment]
You mean using `cargo publish` or on github directly ? Actually i coudn't find any workflow for release even inside `ntex` i'm not sure how you handle it

**Pull request merged**
